# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-06 15:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20160606_1011'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipeingredient',
            options={},
        ),
        migrations.RemoveField(
            model_name='recipeingredient',
            name='name',
        ),
    ]
